# Create express database service

version: '3.8'

services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - universalwrapper_volume:/var/lib/mysql
    environment:
      - MYSQL_USER=king
      - MYSQL_PASSWORD=application_dev
      - MYSQL_DATABASE=universalwrapper

volumes:
  universalwrapper_volume: