version: '3.8'

services:
  universalwrapper_database:
    image: mysql:5.6
    container_name: universalwrapper_database
    ports:
      - "3306:3306"
    volumes:
      - universalwrapper_volume:/var/lib/mysql
    environment:
      - MYSQL_USER=king
      - MYSQL_ROOT_PASSWORD=application_dev
      - MYSQL_DATABASE=universalwrapper

volumes:
  universalwrapper_volume: