connection:
  mysql:
    hostname: ""
    database: universalwrapper
    user: sa
    password: sa
#  mysql:
#    hostname: "localhost:3306"
#    database: universalwrapper
#    user: root
#    password: test