name: 'gradle-workflow'

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build gradle project
        run: |
          gradle clean shadowJar

      - name: Setup project version
        run: |
          export PROJECT_VERSION=$(gradle properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
          echo "Debug gradle version ${PROJECT_VERSION}"
          echo "PROJECT_VERSION=${PROJECT_VERSION}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PROJECT_VERSION }}
          release_name: "${{ format('{0} [Release #{1}]', github.event.head_commit.message, github.run_id) }}"
          body: |
            [jitpack-url]: https://jitpack.io/#${{ github.repository }}/${{ env.PROJECT_VERSION }}
          draft: false
          prerelease: false

      - name: Uploud release assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/*.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ env.PROJECT_VERSION }}