name: 'gradle-workflow'

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup project version
        run: |
          export PROJECT_VERSION=$(gradle properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')
          echo "Debug maven gradle version ${PROJECT_VERSION}"
          echo "PROJECT_VERSION=${PROJECT_VERSION}" >> $GITHUB_ENV
